### ISSUE TITLE
Design Database Structure for Friends List

### ISSUE THREAD

**Issue by mzhang54** [cse442-at-ub/cse442-semester-project-368#16]
We need to design database structure to (1) manage friends list per user, and (2) check all the users' connections.

**Comment by cjw531** [comment]
### Task Test

1. Each of the user should be having a database that has a list of friends.
2. The list of friends should be showing in the user's friend list.

**Comment by cjw531** [comment]
### Task Test

As a group discussed, we concluded to use this table below as our database structure to friends' list:
```
| user_id_1 | friend_id_1 |
| user_id_1 | friend_id_2 |
| user_id_2 | friend_id_1 |
| user_id_3 | friend_id_5 |
```
References: https://dba.stackexchange.com/questions/135941/designing-a-friendships-database-structure-should-i-use-a-multivalued-column

For example:
```
|     Jim    |  Andrew  |
|     Jim    |   John   |
|   Andrew   |   Jim    |
|    John    |   Jim    |
```

Our team decided to save users' friends information as above. Since SQL does not allow storing a list format, so we decided to store by user's id in both ways like stated in above tables.

Thus, for the listing down the user's friend list, we get the current logged-in user's user id, and fetch the friends list based on the current user id.

Note that this database will allow to do:
- Each of the user should be having a database that has a list of friends.
- The list of friends should be showing in the user's friend list.
- If A adds B, then it will be stored as: | A | B |, but it will be automatically stored in the other way around too: | B | A |.
