### ISSUE TITLE
Add My Schedule

### ISSUE THREAD

**Issue by dr72** [cse442-at-ub/cse442-semester-project-368#2]
As a person with a changing schedule, I want to add an appointment to my calendar and schedule, so my groups know I am not available at the time.

**Comment by cjw531** [comment]
### Acceptance Test

1. Navigate to the "My Schedule" page.
2. Press the floating button located bottom right corner.
3. Input necessary data to create your schedule -such as: title, start time, end time, end date, and description.
4. Note that you cannot add a start date here because you can only add a schedule starting from today in "My Schedule" page. If you wish to create a schedule that can have a varying starting date, you should go to "Calendar" page.
5. Once done with inputting data, save your schedule.
6. Your schedule should now be up-to-date and should be displayed in both "My Schedule" page as well as "Calendar" page.
