### ISSUE TITLE
Appointment/Meeting -Make Appointment

### ISSUE THREAD

**Issue by HaoZiOwO** [cse442-at-ub/cse442-semester-project-368#22]
Create appointment with a friend, or with multiple friends. Once the user clicks friend(s) and click create appointment button, it should show list of available time slots. To request an appointment on that time, the user can click the time slot and send a request.

**Comment by cjw531** [comment]
### Task Test

- Display the friends list with names & emails, and allow onclick. Refer to friends tab (#82) for retrieving friends list database.
- Implement search bar (as we did for Friends menu) so that the user can search and select.
- Clicking a floating action button on the right-bottom corner should open up a new activity screen for setting up a new appointment. If the user did not select any of the friends, show toast message and guide them to click friends to make an appointment request.
- In the activity screen (for the one that we actually send request, not for the one that we provide available time slot), make sure to implement the custom toolbar (the one that we used for Add Daily Schedule and Add Monthly Schedule); and allow users to exit if they click 'cancel' and request for a meeting if they click 'save'.
- The activity screen for showing available time slot should have a date picker dialog for the user to set up a start date.
- Make a wheel-picker/ **or** dropdown menu below, to ask for the duration of the meeting. The minimum is 30min, and the maximum will be 10 hours.
*Note on wheel picker: https://stackoverflow.com/questions/33053765/how-to-make-a-wheel-picker/39662187#39662187
- Once they fill out those two informations, they should be seeing a list of available time slots below (like how we did for Monthly schedule list when we click a single day).
- If user pick a single time slot (cannot click more than one, or less than one), allow them to save; otherwise, print out toast message and guide them to click one time slot.
- Guide to the new activity screen, which is similar to the add to schedule activity screen (#45), but now it's showing participants as well.
- Prompt the user to write title, start time (between the available times), and then display from and to field based on the start time that the user selected.
- Once they click 'cancel', cancel and go back to the activity where shows available time slots.
- Once they click 'save', request a meeting to others -add this to the database as designed (#112)
- Exit back to the fragment once the user press 'save', and reset all the list that are clicks which they clicked before.
- Add some mock appointment via Android application and compare whether it gets added properly or not on myphpadmin or thru cheshire server on terminal.
