### ISSUE TITLE
UI: Calendar onClick Pop-up Options

### ISSUE THREAD

**Issue by HaoZiOwO** [cse442-at-ub/cse442-semester-project-368#27]
We need to ask user to edit/delete the schedule when the click the certain schedule that they currently inputted. The pop-up options menu will be an ideal. This menu options are for the "Calendar" page.

**Comment by cjw531** [comment]
### Task Test:

1. Open the application.
2. Login with any characters for email and any password > 5 characters.
3. Go to calendar page using navigation menu in top left.
4. Click one of the existing schedule from "Calendar" page.
5. It will give you an option whether to edit or delete the selected schedule.

*Features of edit/delete are not implemented yet because we need to design the database structure first to update the information.
