### ISSUE TITLE
Add Schedule Floating Button in "My Schedule"

### ISSUE THREAD

**Issue by HaoZiOwO** [cse442-at-ub/cse442-semester-project-368#37]
Create a floating button in "My Schedule" page so that the user can add schedules for the day. Note that this only supports for today, not the future appointments.

**Comment by cjw531** [comment]
### Task Test:

1. Open the application; login with any characters for email and any password > 5 characters,  you should be in "My Schedule" page -if you are in different page, use the navigation bar on top left corner to go to "My Schedule" page.
2. Once you navigate, it will show you a list of schedule with the "Add Daily Schedule" floating button in the bottom right corner, colored in pink.

*It shows add activity screen but it is not fully implemented yet, because we have not designed the database yet.
