### ISSUE TITLE
UI: Calendar Create a Button to Add Schedule

### ISSUE THREAD

**Issue by HaoZiOwO** [cse442-at-ub/cse442-semester-project-368#40]
In calendar, we need to make a button to add schedule. Unlike the button from "Today", the add-able date is not restricted to the current day.

**Comment by cjw531** [comment]
### Task Test:

1. Open the application
2. Login with any characters for email and any password > 5 characters.
3. If you are in different page, use the navigation bar on top left corner to go to "Calendar" page.
4. Once you navigate, it will show you a calendar and some existing schedule (if exists). 
5. Click "Add Schedule" floating button in the bottom right corner to add schedule.

*It shows add activity screen but it is not fully implemented yet, because we have not designed the database yet.
