### ISSUE TITLE
UI My Schedule: Pop-Up Menu when Click the schedule

### ISSUE THREAD

**Issue by HaoZiOwO** [cse442-at-ub/cse442-semester-project-368#46]
Create a menu options when the user click the schedule. This menu options allows user to remove/cancel their daily schedule.

**Comment by cjw531** [comment]
### Task Test:

1. Open the application
2. Login with any characters for email and any password > 5 characters.
3. Click one of the existing schedule from "My Schedule" page.
4. It will give you an option whether to edit or delete the selected schedule.

*Features of edit/delete are not implemented yet because we need to design the database structure first to update the information.
