### ISSUE TITLE
Edit My Schedule

### ISSUE THREAD

**Issue by mzhang54** [cse442-at-ub/cse442-semester-project-368#47]
As a user with a changing schedule, I want to modify appointments, so I can view an updated schedule.

**Comment by cjw531** [comment]
### Acceptance Test

1. Navigate to the "My Schedule" page.
2. Press the existing schedule -which you would like to edit- from your daily schedule list. *Note that you should go to "Calendar" page to edit schedules other than the daily one.
3. An option window should pop up to you to select between: "Edit" and "Delete"
4. Press "edit" here.
5. A new input window will pop up so that you can edit your existing data. Feel free to edit the followings: title, start time, end time, end date, details.
6. Once you click save, your  "My Schedule" page should be up-to-dated based on your input.
