### ISSUE TITLE
Friends -Add Friends from the Existing User List

### ISSUE THREAD

**Issue by mzhang54** [cse442-at-ub/cse442-semester-project-368#61]
Among the existing user list that we have on MySQL database, we need to allow users to add friends with this information in "Friends" page.

**Comment by cjw531** [comment]
### Task Test

- Display the whole user list when the user opens add friend screen by clicking the floating button in "Friends" screen.
- User list is displayed as: (All user) - (Added friends) = All of the registered users who are not friends with the signed-in user
- Create a search bar similar to (#72); allow users to search people via name & email address -in case where there are two people with the same name.
- Enable onclick on user list, and once the user clicks one of them, make a pop-up window to re-confirm the user whether you would like to add this another user as your friend or not.
- If the user clicks yes, then add them in the database, based on the designed SQL table structure (#16). Otherwise, cancel it.
- Note that the add friend working as follows: A adds B, reflects on A's friends list, but it also does the other way around like B's friends list has A's name in it.
